S3C_MVC/S3C_MVC/Controllers/ContactUsController.cs
using S3C_MVC.DataLayer;
using S3C_MVC.Models;
using S3C_MVC.Models.Public;
using S3C_MVC.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace S3C_MVC.Controllers
{
    public class ContactUsController : Controller
    {
        public ContactUsMessagesServices contactUsMessagesServices => new ContactUsMessagesServices();

        // GET: ContactUs
        [HttpGet]
        public ViewResult Index()
        {
            ViewBag.Title = "تماس با ما";

            return View();
        }

        [HttpPost]
        public ViewResult Index(ContactUsModel model)
        {
            if (model.Firstname == "ali")
                ModelState.AddModelError("aaa", "لطفا علی نباش!");

            if (ModelState.IsValid)
            {
                ContactUsModel.List.Add(model);

                // insert

                ViewBag.IsSuccess = true;
            }

            System.Threading.Thread.Sleep(5000);

            return View();
        }

        public bool SendMessage(ContactUsMessage contactUsMessage)
        {
            try
            {
                contactUsMessagesServices.Insert(contactUsMessage);
                System.Threading.Thread.Sleep(5000);

                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
}

S3C_MVC/S3C_MVC/Views/ContactUs/Index.cshtml
@model S3C_MVC.DataLayer.ContactUsMessage

<h3 class="subtitle">محل ما</h3>
<div class="row">
    <div class="col-sm-3"><img src="/image/product/store_location-275x180.jpg" alt="قالب مارکت شاپ" title="قالب مارکت شاپ" class="img-thumbnail" /></div>
    <div class="col-sm-3">
        <strong>قالب مارکت شاپ</strong><br />
        <address>
            میدان مرکزی،<br />
            خیابان وینگ شماره 22،<br />
            نیویورک،<br />
            ایالات متحده
        </address>
    </div>
    <div class="col-sm-3">
        <strong>شماره تلفن</strong><br>
        +91 9898989898<br />
        <br />
        <strong>فکس</strong><br>
        +91 9898989898
    </div>
    <div class="col-sm-3">
        <strong>ساعات کار</strong><br />
        خدمات مشتریان 24x7<br />
        <br />
        <strong>دیدگاه ها</strong><br />
        در اینجا توضیحات دلخواه خود را قرار دهید. فروشگاه چک قبول نمیکند!
    </div>
</div>

<div style="position: relative;">
    @using (Html.BeginForm("Index", "ContactUs", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="loading">
            <img src="~/image/progress.gif" />
        </div>

        if (ViewBag.IsSuccess == true)
        {
            <div class="alert alert-success">ثبت با موفقیت انجام شد.</div>
        }

        <fieldset>
            @Html.ValidationSummary(false);
            <h3 class="subtitle">با ما ارتباط برقرار کنید</h3>
            <div class="form-group required">
                @Html.LabelFor(a => a.Firstname, new { @class = "col-md-2 col-sm-3 control-label" })
                <div class="col-md-10 col-sm-9">
                    @Html.TextBoxFor(a => a.Firstname, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.Firstname)
                </div>
            </div>
            <div class="form-group required">
                <label class="col-md-2 col-sm-3 control-label" for="input-email">آدرس ایمیل</label>
                <div class="col-md-10 col-sm-9">
                    @Html.TextBoxFor(a => a.Email, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.Email)
                </div>
            </div>
            <div class="form-group required">
                <label class="col-md-2 col-sm-3 control-label" for="input-enquiry">پرسش</label>
                <div class="col-md-10 col-sm-9">
                    @Html.TextAreaFor(a => a.Message, new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.Message)
                </div>
            </div>
        </fieldset>
        <div class="buttons">
            <div class="pull-right">
                <input class="btn btn-primary btn-contactus" type="submit" value="ارسال" />
            </div>
        </div>
    }
</div>

@section LeftColumn {
    @Html.Partial("_SpecialContent", model: "me me")
}

@section Scripts {
    <script src="~/js/contactus.js"></script>
}